[package]
name = "adjustd"
version = "0.1.0"
authors = ["Ace Eldeib <alexeldeib@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
anyhow = "1.0"
eyre = "0.4"
