trigger:
  branches:
    include: ["*"]

pr:
  branches:
    include: ["*"]

jobs:
- job: build + test
  pool: ace-test
  timeoutInMinutes: 360 # 6 hours
  workspace:
    clean: all
  steps:
  - bash: |
      ./e2e.sh
    displayName: run 
  - bash: | 
      df -h
    displayName: debug
    condition: always()
